name: Code Style

on: [push, pull_request]

jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Git Pull
              run: git pull

            - name: Install
              run: yarn install
              env:
                  CI: true

            - name: Run ESLint (pages)
              run: yarn lint

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply ESLint Fixes
